[package]
name = "terminal-tui"
version = "0.1.0"
authors = ["Kirill Ivanov <bragov4ik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
chrono = "0.4.19"
rand = "0.8.3"