[package]
<<<<<<< HEAD
name = "terminal-test"
version = "0.1.0"
authors = ["Kirill Ivanov <bragov4ik@hotmail.com>"]
=======
name = "terminal-tui"
version = "0.1.0"
authors = ["Kirill Ivanov <bragov4ik@gmail.com>"]
>>>>>>> origin/master
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
crossterm = "0.19.0"
=======
crossterm="0.19.0"
>>>>>>> origin/master
